version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/srv/app
    ports:
      - "0.0.0.0:8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    command: -p 5432

volumes:
  static-data:
  postgresql-data: